#!/usr/bin/env bash

set -e


mkdir -p data/rs0-0 data/rs0-1 data/rs0-2
cp setup/replicaSet.copy setup/replicaSet.js

IP=$(hostname -I | grep -o '192\.168\.[0-9]\{1,3\}\.[0-9]\{1,3\}\|10\.[0-9]\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | head -n 1)

sed -i "s/<HOST_NETWORK_IP>/$IP/g" setup/replicaSet.js

docker-compose up --build -d

echo "host_ip is: $IP"
echo "GUI: http://$IP:1234"
echo "Mongo Connection String: mongodb://$IP:27010,$IP:27011,$IP:27012/?replicaSet=rs0"
