version: "3"
services:
  mongo-rs0-0:
    container_name: m-0
    image: mongo:4
    expose:
      - 27017
    ports:
      - 27010:27017
    volumes:
      - ./data/rs0-0:/data/db
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    depends_on:
      - "mongo-rs0-1"
      - "mongo-rs0-2"

  mongo-rs0-1:
    container_name: m-1
    image: mongo:4
    expose:
      - 27017
    ports:
      - 27011:27017
    volumes:
      - ./data/rs0-1:/data/db
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongo-rs0-2:
    container_name: m-2
    image: mongo:4
    expose:
      - 27017
    ports:
      - 27012:27017
    volumes:
      - ./data/rs0-2:/data/db
    restart: always
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  setup-rs:
    image: "setup-rs"
    build: ./setup
    entrypoint: ["/bin/bash", "./setup.sh"]
    depends_on:
      - "mongo-rs0-0"

  adminmongo:
    image: "mrvautin/adminmongo"
    container_name: m-ui
    environment:
      - HOST=0.0.0.0
    ports:
      - "1234:1234"
    restart: always
